variable "tenant" {}
variable "name" {}
variable "environment" {}
variable "vpc_id" {}
variable "cidr_block" {}
variable "pvt_subnet_ids" {}
variable "eks_subnet_ids" {}
variable "eks_version" {}
variable "vpccni_version" {}
variable "coredns_version" {}
variable "kubeproxy_version" {}
variable "main_capacity_type" {}
variable "extra_capacity_type" {}
variable "main_disk_size" {}
variable "extra_disk_size" {}
variable "main_instance_types" {}
variable "extra_instance_types" {}
variable "main_scaling_config" {}
variable "extra_scaling_config" {}
variable "enable_aws_cicd" {}